import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'imperial-gold': '#D4AF37',
        'imperial-gold-light': '#F4D03F',
        'imperial-gold-dark': '#B8860B',
        'vermillion': '#C41E3A',
        'vermillion-light': '#E63946',
        'vermillion-dark': '#8B0000',
        'celestial-blue': '#4A90D9',
        'celestial-blue-dark': '#2E5984',
        'celestial-blue-light': '#6BA3E0',
        'ink-black': '#000000',
        'ink-dark': '#0A0A0F',
        'ink-medium': '#12121A',
        'ink-light': '#1A1A25',
        'wood-green': '#228B22',
        'fire-red': '#DC143C',
        'earth-yellow': '#DAA520',
        'metal-white': '#C0C0C0',
        'water-blue': '#4169E1',
        'success-jade': '#22C55E',
        'warning-amber': '#F59E0B',
        'danger-vermillion': '#EF4444',
        'info-sapphire': '#3B82F6',
        'primary': '#C41E3A',
        'primary-light': '#E63946',
        'primary-dark': '#8B0000',
        'gold': '#D4AF37',
        'gold-light': '#F4D03F',
        'gold-dark': '#B8860B',
        'bg-dark': '#0A0A0F',
        'bg-medium': '#12121A',
        'bg-light': '#1A1A25',
        'bg-card': '#1E1E2A',
        'bg-elevated': '#252530',
        'text-primary': '#F5F5F5',
        'text-secondary': '#A0A0B0',
        'text-muted': '#6B6B7B',
        'text-disabled': '#4A4A5A',
        'border': '#2A2A3A',
        'border-light': '#3A3A4A',
      },
      fontFamily: {
        'song': ['Noto Serif SC', 'SimSun', 'STSong', 'serif'],
        'kai': ['KaiTi', 'STKaiti', 'Noto Serif SC', 'serif'],
        'mono': ['JetBrains Mono', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      boxShadow: {
        'card': '0 4px 20px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        'gold-glow': '0 0 20px rgba(212, 175, 55, 0.3)',
        'gold-glow-intense': '0 0 20px rgba(212, 175, 55, 0.3), 0 0 40px rgba(212, 175, 55, 0.2), 0 0 60px rgba(212, 175, 55, 0.1)',
        'red-glow': '0 0 15px rgba(196, 30, 58, 0.25)',
        'blue-glow': '0 0 20px rgba(74, 144, 217, 0.3)',
      },
      animation: {
        'float': 'float 6s ease-in-out infinite',
        'pulse-gold': 'pulseGold 3s ease-in-out infinite',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
        'fade-in-up': 'fadeInUp 0.6s ease-out forwards',
        'slide-up': 'slideUp 0.4s ease-out forwards',
        'slide-down': 'slideDown 0.4s ease-out forwards',
        'shake': 'shake 0.5s ease-in-out',
        'shake-intense': 'shakeIntense 0.6s ease-in-out',
        'spin-slow': 'spin 8s linear infinite',
        'pulse-subtle': 'pulseSubtle 2s ease-in-out infinite',
        'glow-pulse': 'glowPulse 2s ease-in-out infinite',
        'star-appear': 'starAppear 1s ease-out forwards',
        'fire-burn': 'fireBurn 1.5s ease-in-out infinite',
        'ripple': 'ripple 1.2s ease-out infinite',
        'yin-yang-rotate': 'yinYangRotate 8s linear infinite',
        'bounce-gentle': 'bounceGentle 2s ease-in-out infinite',
      },
      keyframes: {
        float: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        pulseGold: {
          '0%, 100%': { boxShadow: '0 0 10px rgba(212, 175, 55, 0.2)' },
          '50%': { boxShadow: '0 0 25px rgba(212, 175, 55, 0.5)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '25%': { transform: 'translateX(-3px)' },
          '75%': { transform: 'translateX(3px)' },
        },
        shakeIntense: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-4px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(4px)' },
        },
        pulseSubtle: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.7' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 10px rgba(212, 175, 55, 0.2)', transform: 'scale(1)' },
          '50%': { boxShadow: '0 0 30px rgba(212, 175, 55, 0.6), 0 0 50px rgba(212, 175, 55, 0.3)', transform: 'scale(1.02)' },
        },
        starAppear: {
          '0%': { opacity: '0', transform: 'scale(0.5)', filter: 'blur(10px)' },
          '50%': { opacity: '0.8', filter: 'blur(2px)' },
          '100%': { opacity: '1', transform: 'scale(1)', filter: 'blur(0)' },
        },
        fireBurn: {
          '0%, 100%': { opacity: '0.7', filter: 'brightness(1) saturate(1)', transform: 'scaleY(1)' },
          '25%': { opacity: '0.9', filter: 'brightness(1.2) saturate(1.2)', transform: 'scaleY(1.05)' },
          '50%': { opacity: '1', filter: 'brightness(1.4) saturate(1.4)', transform: 'scaleY(1.1)' },
          '75%': { opacity: '0.9', filter: 'brightness(1.2) saturate(1.2)', transform: 'scaleY(1.05)' },
        },
        ripple: {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(1.5)', opacity: '0' },
        },
        yinYangRotate: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        bounceGentle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-5px)' },
        },
      },
      backgroundImage: {
        'gradient-imperial-gold': 'linear-gradient(135deg, #F4D03F 0%, #D4AF37 50%, #B8860B 100%)',
        'gradient-cosmic-deep': 'radial-gradient(ellipse at center, #1A1A25 0%, #0A0A0F 70%, #000000 100%)',
        'gradient-primary': 'linear-gradient(135deg, #C41E3A 0%, #8B0000 100%)',
        'gradient-card': 'linear-gradient(145deg, #1E1E2A 0%, #12121A 100%)',
      },
      backdropBlur: {
        'aurora': '10px',
      },
    },
  },
  plugins: [],
};

export default config;
